spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    username: root
    url: jdbc:mysql://127.0.0.1/mytb?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
  jpa:
    show-sql: true
  mvc:
    static-path-pattern: /**

    #    throw-exception-if-no-handler-found: true
    #  resources:
    #    add-mappings: false

    #全局配置，当返回给前端的对象的字段为null时，该字段不参与序列化
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /mytb

wechat:
  mpAppId: wxa4692610df651f64
  mpAppSecret: a5fc80796d18a4fca7e58fc46db67441
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:/Users/Administrator/Downloads/h5.p12
  notifyUrl: http://mytb.nat300.top/mytb/Wechatpay/payNotify

#项目的域名
address:
  url: http://mytb.nat300.top
